"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useSession } from "@/lib/auth-client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Edit3, ExternalLink, ImagePlus, Plus, Trash2, Video, X, Archive } from "lucide-react";

export type Game = { id: string; title: string; status: string; description: string; image: string; videoUrl: string; gameUrl: string; accent: "primary" | "secondary" | "accent"; cta: string };
const emptyGame: Omit<Game, "id"> = { title: "", status: "Now Forging", description: "", image: "", videoUrl: "", gameUrl: "", accent: "primary", cta: "Enter the Realm" };
const validUrl = (value: string) => { try { const u = new URL(value); return ["http:", "https:"].includes(u.protocol) ? value : ""; } catch { return ""; } };

export default function GameManager({ defaults }: { defaults: Game[] }) {
  const { data: session, isPending } = useSession();
  const isAdmin = session?.user?.email?.toLowerCase() === "kalebmay18@gmail.com";
  const [games, setGames] = useState<Game[]>(defaults), [editing, setEditing] = useState<Game | null>(null), [draft, setDraft] = useState<Omit<Game, "id">>(emptyGame), [open, setOpen] = useState(false), [loaded, setLoaded] = useState(false), [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/games").then(r => r.json()).then(data => { if (Array.isArray(data) && data.length) setGames(data); setLoaded(true); }).catch(() => setLoaded(true)); }, []);
  const persist = async (next: Game[]) => { setGames(next); const response = await fetch("/api/games", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(next) }); if (!response.ok) setMessage("Could not save changes."); else setMessage("Changes published."); };
  const save = async () => { if (!isAdmin || !draft.title.trim() || !draft.description.trim()) return; const game = { ...draft, id: editing?.id ?? crypto.randomUUID(), title: draft.title.trim() } as Game; await persist(editing ? games.map(g => g.id === editing.id ? game : g) : [...games, game]); setOpen(false); };
  const remove = async (id: string) => { if (isAdmin && confirm("Remove this game from the published site?")) await persist(games.filter(g => g.id !== id)); };
  const purge = async () => { if (!confirm("Purge media files not used by any game? This cannot be undone.")) return; const response = await fetch("/api/games", { method: "DELETE" }); const data = await response.json(); setMessage(response.ok ? `Purged ${data.purged ?? 0} unused file(s).` : "Purge failed."); };
  const readImage = (file: File) => { const reader = new FileReader(); reader.onload = () => setDraft(d => ({ ...d, image: String(reader.result) })); reader.readAsDataURL(file); };
  if (isPending || !loaded) return <div className="py-8 text-center text-muted-foreground">Loading published realms...</div>;
  return <>
    <div className="mb-10 flex flex-wrap items-center justify-between gap-4 border border-white/10 bg-card/40 p-5"><div><p className="font-bold uppercase tracking-widest text-muted-foreground">{isAdmin ? "Realm archive" : "Published realms"}</p><p className="text-sm text-muted-foreground">{isAdmin ? "Manage published games, artwork, and links." : "Content updates are managed by the studio."}</p>{message && <p className="mt-2 text-sm text-primary" role="status">{message}</p>}</div>{isAdmin ? <div className="flex gap-2"><Button variant="outline" onClick={purge}><Archive data-icon="inline-start" /> Purge unused files</Button><Button onClick={() => { setEditing(null); setDraft(emptyGame); setOpen(true); }}><Plus data-icon="inline-start" /> Add game</Button></div> : <Button asChild variant="outline"><Link href="/sign-in">Admin sign in</Link></Button>}</div>
    <div className="flex flex-col gap-24">{games.map((game, i) => <article key={game.id} className="grid grid-cols-1 items-center gap-12 lg:grid-cols-2"><div className={`relative ${i % 2 ? "lg:order-2" : ""}`}>{game.image ? <img src={game.image} alt={game.title} className="aspect-video w-full rounded-sm border border-white/10 object-cover" onError={e => { e.currentTarget.style.display = "none"; }} /> : <div className="flex aspect-video items-center justify-center border border-dashed border-white/20 text-muted-foreground">No artwork uploaded</div>}</div><div className={`flex flex-col gap-5 ${i % 2 ? "lg:order-1" : ""}`}><p className="font-bold uppercase tracking-widest text-primary">{game.status}</p><h3 className="cinzel text-4xl font-black">{game.title.toUpperCase()}</h3><p className="text-lg leading-relaxed text-muted-foreground">{game.description}</p><div className="flex flex-wrap gap-3">{validUrl(game.gameUrl) && <Button asChild><a href={validUrl(game.gameUrl)} target="_blank" rel="noreferrer">{game.cta} <ExternalLink data-icon="inline-end" /></a></Button>}{validUrl(game.videoUrl) && <Button asChild variant="outline"><a href={validUrl(game.videoUrl)} target="_blank" rel="noreferrer"><Video data-icon="inline-start" /> Trailer <ExternalLink data-icon="inline-end" /></a></Button>}</div>{isAdmin && <div className="flex flex-wrap gap-2 border-t border-white/10 pt-4"><Button size="sm" variant="outline" onClick={() => { setEditing(game); setDraft({ ...emptyGame, ...game }); setOpen(true); }}><Edit3 data-icon="inline-start" /> Edit</Button><Button size="sm" variant="destructive" onClick={() => remove(game.id)}><Trash2 data-icon="inline-start" /> Remove</Button></div>}</div></article>)}</div>
    {isAdmin && <div className="mt-16 text-center"><Button variant="ghost" onClick={() => persist(defaults)}>Reset original realms</Button></div>}
    {isAdmin && open && <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 flex items-center justify-center bg-background/90 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto border border-primary/40 bg-card p-6"><div className="mb-6 flex justify-between"><h2 className="cinzel text-2xl font-bold">{editing ? "Edit realm" : "Add realm"}</h2><Button variant="ghost" size="icon" onClick={() => setOpen(false)} aria-label="Close editor"><X /></Button></div><div className="flex flex-col gap-4"><label className="flex flex-col gap-2">Title<Input value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} /></label><label className="flex flex-col gap-2">Status<Input value={draft.status} onChange={e => setDraft({ ...draft, status: e.target.value })} /></label><label className="flex flex-col gap-2">Description<Textarea value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })} /></label><label className="flex flex-col gap-2">Button label<Input value={draft.cta} onChange={e => setDraft({ ...draft, cta: e.target.value })} /></label><label className="flex flex-col gap-2">Game URL<Input type="url" value={draft.gameUrl} onChange={e => setDraft({ ...draft, gameUrl: e.target.value })} placeholder="https://..." /></label><label className="flex flex-col gap-2">Video URL<Input type="url" value={draft.videoUrl} onChange={e => setDraft({ ...draft, videoUrl: e.target.value })} /></label><label className="flex flex-col gap-2">Artwork file<Input type="file" accept="image/*" onChange={e => e.target.files?.[0] && readImage(e.target.files[0])} /><span className="text-xs text-muted-foreground">Stored in Neon as image data. {draft.image ? "Artwork ready." : "No artwork selected."}</span></label><div className="flex justify-end gap-3"><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={save}><ImagePlus data-icon="inline-start" /> Save published game</Button></div></div></div></div>}
  </>;
}
