"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useSession } from "@/lib/auth-client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Edit3, ExternalLink, ImagePlus, Plus, Trash2, Video, X } from "lucide-react";
export type Game = { id: string; title: string; status: string; description: string; image: string; videoUrl: string; accent: "primary" | "secondary" | "accent"; cta: string };
const emptyGame: Omit<Game,"id"> = { title:"", status:"Now Forging", description:"", image:"", videoUrl:"", accent:"primary", cta:"Enter the Realm" };
const validUrl=(value:string)=>{try{const u=new URL(value);return ["http:","https:"].includes(u.protocol)?value:""}catch{return ""}};
export default function GameManager({defaults}:{defaults:Game[]}) {
 const {data:session,isPending}=useSession(); const isAdmin=session?.user?.email?.toLowerCase()==="kalebmay18@gmail.com"; const [games,setGames]=useState<Game[]>(defaults); const [editing,setEditing]=useState<Game|null>(null); const [draft,setDraft]=useState<Omit<Game,"id">>(emptyGame); const [open,setOpen]=useState(false); const [loaded,setLoaded]=useState(false); const [viewing,setViewing]=useState<Game|null>(null);
 useEffect(()=>{fetch("/api/games").then(r=>r.json()).then((data)=>{if(Array.isArray(data)&&data.length)setGames(data);setLoaded(true)}).catch(()=>setLoaded(true))},[]);
 const persist=async(next:Game[])=>{setGames(next);if(isAdmin)await fetch("/api/games",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)})};
 const save=async()=>{if(!isAdmin||!draft.title.trim()||!draft.description.trim())return;const game={...draft,id:editing?.id??crypto.randomUUID(),title:draft.title.trim()} as Game;await persist(editing?games.map(g=>g.id===editing.id?game:g):[...games,game]);setOpen(false)};
 const remove=async(id:string)=>{if(isAdmin&&confirm("Remove this game from the published site?"))await persist(games.filter(g=>g.id!==id))};
 if(isPending||!loaded)return <div className="py-8 text-center text-muted-foreground">Loading published realms...</div>;
 return <><div className="mb-10 flex items-center justify-between border border-white/10 bg-card/40 p-5"><div><p className="font-bold uppercase tracking-widest text-muted-foreground">{isAdmin?"Realm archive":"Published realms"}</p><p className="text-sm text-muted-foreground">{isAdmin?"Manage published games, artwork, and trailer links.":"Content updates are managed by the studio."}</p></div>{isAdmin?<Button onClick={()=>{setEditing(null);setDraft(emptyGame);setOpen(true)}}><Plus data-icon="inline-start"/> Add game</Button>:<Button asChild variant="outline"><Link href="/sign-in">Admin sign in</Link></Button>}</div>
 <div className="flex flex-col gap-24">{games.map((game,i)=><article key={game.id} className="grid grid-cols-1 items-center gap-12 lg:grid-cols-2"><div className={`relative ${i%2?"lg:order-2":""}`}>{game.image?<img src={game.image} alt={game.title} className="aspect-video w-full rounded-sm border border-white/10 object-cover"/>:<div className="flex aspect-video items-center justify-center border border-dashed border-white/20 text-muted-foreground">No artwork</div>}</div><div className={`flex flex-col gap-5 ${i%2?"lg:order-1":""}`}><p className="font-bold uppercase tracking-widest text-primary">{game.status}</p><h3 className="cinzel text-4xl font-black">{game.title.toUpperCase()}</h3><p className="text-lg leading-relaxed text-muted-foreground">{game.description}</p><div className="flex flex-wrap gap-3"><Button onClick={()=>setViewing(game)}>{game.cta}</Button>{validUrl(game.videoUrl)&&<Button asChild variant="outline"><a href={validUrl(game.videoUrl)} target="_blank" rel="noreferrer"><Video data-icon="inline-start"/> Trailer <ExternalLink data-icon="inline-end"/></a></Button>}</div>{isAdmin&&<div className="flex flex-wrap gap-2 border-t border-white/10 pt-4"><Button size="sm" variant="outline" onClick={()=>{setEditing(game);setDraft({...game});setOpen(true)}}><Edit3 data-icon="inline-start"/> Edit</Button><Button size="sm" variant="destructive" onClick={()=>remove(game.id)}><Trash2 data-icon="inline-start"/> Remove</Button></div>}</div></article>)}</div>
 {isAdmin&&<div className="mt-16 text-center"><Button variant="ghost" onClick={()=>persist(defaults)}>Reset original realms</Button></div>}
 {viewing&&<div role="dialog" aria-modal="true" aria-label={`${viewing.title} overview`} className="fixed inset-0 z-50 flex items-center justify-center bg-background/90 p-4" onClick={()=>setViewing(null)}><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto border border-primary/40 bg-card" onClick={e=>e.stopPropagation()}>{viewing.image?<img src={viewing.image} alt={viewing.title} className="aspect-video w-full object-cover"/>:<div className="flex aspect-video items-center justify-center border-b border-white/10 text-muted-foreground">No artwork</div>}<div className="flex flex-col gap-4 p-6"><div className="flex items-start justify-between gap-4"><div><p className="font-bold uppercase tracking-widest text-primary">{viewing.status}</p><h2 className="cinzel text-3xl font-black leading-tight">{viewing.title.toUpperCase()}</h2></div><Button variant="ghost" size="icon" onClick={()=>setViewing(null)} aria-label="Close overview"><X/></Button></div><p className="text-lg leading-relaxed text-muted-foreground">{viewing.description}</p><div className="flex flex-wrap gap-3 border-t border-white/10 pt-4">{validUrl(viewing.videoUrl)&&<Button asChild variant="outline"><a href={validUrl(viewing.videoUrl)} target="_blank" rel="noreferrer"><Video data-icon="inline-start"/> Watch trailer <ExternalLink data-icon="inline-end"/></a></Button>}<Button variant="ghost" onClick={()=>setViewing(null)}>Close</Button></div></div></div></div>}
 {open&&<div role="dialog" aria-modal="true" className="fixed inset-0 z-50 flex items-center justify-center bg-background/90 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto border border-primary/40 bg-card p-6"><div className="mb-6 flex justify-between"><h2 className="cinzel text-2xl font-bold">{editing?"Edit realm":"Add realm"}</h2><Button variant="ghost" size="icon" onClick={()=>setOpen(false)} aria-label="Close editor"><X/></Button></div><div className="flex flex-col gap-4"><label className="flex flex-col gap-2">Title<Input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="flex flex-col gap-2">Status<Input value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}/></label><label className="flex flex-col gap-2">Description<Textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label className="flex flex-col gap-2">Button label<Input value={draft.cta} onChange={e=>setDraft({...draft,cta:e.target.value})}/></label><label className="flex flex-col gap-2">Video URL<Input type="url" value={draft.videoUrl} onChange={e=>setDraft({...draft,videoUrl:e.target.value})}/></label><label className="flex flex-col gap-2">Artwork URL<Input value={draft.image} onChange={e=>setDraft({...draft,image:e.target.value})} placeholder="https://..."/></label><div className="flex justify-end gap-3"><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={save}>Save published game</Button></div></div></div></div>}
 </>;
}
